//模拟dom树
var div = {
    tagName:'div',
    attrs:{
        id:'mydiv',
        title:"说实话",
        'data-index':'0'
    },
    childrens:[
        '我好帅',
        {
            tagName:'p',
            attrs:{},
            childrens:[
                '哈哈哈哈'
            ]
        }
    ]
}
